Objetivo 2 IV-21-22
Antobio17/IV pull request #21
Opened 2021-11-11 19:27 UTC by argelion14

Objetivo 2 de la asignatura Infraestructura Virtual

2021-11-12 09:42 UTC, Antobio17 reviewed
Buen trabajo en general :1st_place_medal:. Te comento dos errores y corrigiéndolos estará listo para la revisión.

2021-11-12 09:42 UTC, Antobio17 commented on my_hairdressing_app/citas.py
> +    """
La entidad _citas_ no puede ser **_frozen_** ya que será la encargada de almacenar las nuevas citas y se modificará su propiedad (de hecho has declarado el método para ello).

2021-11-12 09:42 UTC, Antobio17 commented on my_hairdressing_app/citas.py
> +            Tipo datetime que representa la fecha de la cita
Como bien se dijo en los issue #20 no debería pasarse por parámetros la fecha como _datetime_, si no un parámetro _**día**_: str el cual especificará el dia en el que tiene lugar la cita.

2021-11-12 11:34 UTC, argelion14 commented on my_hairdressing_app/citas.py
> +    """
Efectivamente, fallo mio y corregido

2021-11-12 11:56 UTC, Antobio17 commented
Listo para revisión @JJ.

2021-11-18 08:30 UTC, JJ requested changes
Aparte de lo indicado, por favor comprueba que los issues sean problemas y el resto de la lista de comprobación.

2021-11-18 08:30 UTC, JJ commented on my_hairdressing_app/cita.py
> +            raise AttributeError("El teléfono debe ser una cadena")
El teléfono es un número... Recuerda usar los tipos de la forma correcta.

2021-11-18 08:30 UTC, JJ commented on my_hairdressing_app/cita.py
> +            raise AttributeError("El tipo de cita especificada no es correcta.")
Convendría también que diseñaras tipos de error específicos. No puedes lanzar siempre AttributeError

2021-11-18 08:30 UTC, JJ commented on my_hairdressing_app/cita.py
> +            self._tipo_de_cita = CorteNormal()
¿Aquí aplicas el principio de sustitución de Liskov?

2021-11-18 08:30 UTC, JJ commented on my_hairdressing_app/citas.py
> +from abc import abstractmethod
Uf, a estas alturas, puede ser un poco complicado meter estas dependencias...

2021-11-18 08:30 UTC, JJ commented on my_hairdressing_app/citas.py
> +        NotImplemented
Si has usado abc solo para esto, podías simplemente poner "pass" o levantar una excepción. Cada dependencia tiene peso en una aplicación, y hay que evitarlas si se puede.

2021-11-18 08:34 UTC, argelion14 commented on my_hairdressing_app/cita.py
> +            raise AttributeError("El teléfono debe ser una cadena")
Aquí use un tipo string de acuerdo con el issue #16 donde señala que será de tipo string para admitir los código de país

2021-11-18 08:39 UTC, argelion14 commented on my_hairdressing_app/citas.py
> +        NotImplemented
Elimino la biblioteca abc para poner solo pass

2021-11-18 08:39 UTC, argelion14 commented on my_hairdressing_app/citas.py
> +from abc import abstractmethod
Eliminada

2021-11-18 08:54 UTC, argelion14 commented on my_hairdressing_app/cita.py
> +            self._tipo_de_cita = CorteNormal()
No entiendo donde aplicar la sustitución de Liskov, no existen subclases, son objetos valor que se crean

2021-11-19 06:40 UTC, JJ commented on my_hairdressing_app/cita.py
> +            self._tipo_de_cita = CorteNormal()
Estás asignando objetos valor de diferente tipo a la misma variable. Esos objetos valor ni siquiera descienden de la misma clase base.

2021-11-19 06:41 UTC, JJ commented on my_hairdressing_app/citas.py
> +        NotImplemented
No has hecho el push. Cuando esté listo para revisión, avisa.

2021-11-19 07:49 UTC, Antobio17 commented on my_hairdressing_app/cita.py
> +            self._tipo_de_cita = CorteNormal()
Se podría crear una clase padre abstracta que contenga las propiedades ya que son comunes.
Desde las clases hijas se llamaría al constructor padre con los valores para su inicialización.

2021-11-19 10:41 UTC, Antobio17 commented on my_hairdressing_app/cita.py
> +            raise AttributeError("El tipo de cita especificada no es correcta.")
Añado por [aquí](https://www.programiz.com/python-programming/user-defined-exception) información sobre como crear tipos de errores en _Python_.

2021-11-19 12:14 UTC, Antobio17 reviewed
Te hago algunos apuntes sobre l;a implementación de errores propios.

2021-11-19 12:14 UTC, Antobio17 commented on my_hairdressing_app/errores.py
> +
Veo una buena idea tener un fichero aparte para los errores propios del proyecto, pero creo que podría enfocarse de otra forma:
- No veo necesario crear la clase base para los errores ya que directamente podrías extender el error de _Exception_ tal y como se hace en la clase _Error_.
- En los parámetros pasados al constructor definiría por defecto el mensaje, así si no fuera necesario no habría que estar pasándole constantemente un mensaje a la clase.
- Para el nombre de la clase del error seguiría las buenas prácticas de Python y definiría el nombre en camelcase.
- Por último crearía varios tipos de errores, no solo uno para que sea mas explícito en el propio código. Por ejemplo: si el teléfono no es válido la clase del error podría llamarse PhoneFormatError.

2021-11-19 17:00 UTC, Antobio17 reviewed
Listo para revisión @JJ.

2021-11-21 08:42 UTC, JJ approved these changes
Voy a aprobar porque se ha hecho bastante esfuerzo por seguir los consejos en las revisiones, pero hay bastante errores que se han señalado en los issues y en línea. No se puede pedir más de @argelion14, así que pediría a @Antobio17 que fusionara este PR y que hiciera él mismo los cambios antes del siguiente objetivo.

2021-11-21 08:42 UTC, JJ commented on my_hairdressing_app/cita.py
> +
Este tipo de cosas se solucionan mucho mejor con un diccionario que con un if.

2021-11-21 08:42 UTC, JJ commented on my_hairdressing_app/cita.py
> +
Así además no hay más que cambiar el diccionario si hay nuevos tipos, y puede estar en un fichero de configuración.

2021-11-21 08:42 UTC, JJ commented on my_hairdressing_app/cita.py
> +            raise PhoneFormatError()
¿Sólo hay ese tipo de error? ¿Ves lo que pasa cuando no formulas #22 como un problema? ¿Qué pasa si el teléfono tiene espacios?

2021-11-21 08:42 UTC, JJ commented on my_hairdressing_app/errores.py
> +class CitaNameNotExist (Exception):
El uso de Spanglish en los nombres de las variables no es una buena práctica.

2021-11-21 08:42 UTC, JJ commented on my_hairdressing_app/errores.py
> +        self.message = message
En los dos errores debe usarse la cadena original (o lo que sea) para que se sepa qué es lo que está mal.

2021-11-21 08:42 UTC, JJ commented on my_hairdressing_app/tinte.py
> +class Tinte(tipo_cita):
Los nombres de clases deben seguir siempre la misma convención en Python

2021-11-21 08:42 UTC, JJ commented on my_hairdressing_app/tipo_cita.py
> +class tipo_cita(ABC):
Una clase base no tienes más que declararla en Python; una vez más, no te hacen falta dependencias externas. Y el nombre de la clase no sigue las buenas prácticas.

2021-11-21 18:19 UTC, merged