[IV-21-22] Objetivo 4
Antobio17/IV pull request #28
Opened 2021-11-19 19:21 UTC by Antobio17

Tareas realizadas para completar issues #25, #26, #27:
- Documentación sobre la elección de librería de tests utilizada.
- Funcionalidad para reservar una cita en un dia y turno de trabajo especifico.
- Nuevos tipos de errores para lanzar excepciones.
- Batería de tests para probar el nuevo código incorporado.

2021-11-19 21:46 UTC, Antobio17 commented
Listo para revisión @JJ

2021-11-21 09:13 UTC, JJ requested changes
Un issue para llevar a cabo los tests no puede ser "desarrollo de tests". Tiene que plantear un problema, y se deben hacer commits para resolver cada uno de los problemas que plantee

2021-11-21 09:13 UTC, JJ commented on docs/tests.md
> +En _Python_ existen varios framework y librerías para la construcción de tests, para este proyecto se van a tener en cuenta dos de ellas, **Pytests** y **Unittest**.
Son cosas muy diferentes.

2021-11-21 09:13 UTC, JJ commented on docs/tests.md
> +Las dos herramientas son bastante similares pero para mi hay algo bastante significativo que las diferencia y es la **respuesta de la ejcución** al lanzar estos tests.
No, no lo son, ni se parecen.

2021-11-21 09:13 UTC, JJ commented on docs/tests.md
> +También destacar que según he podido [leer](https://www.pythonpool.com/python-unittest-vs-pytest/), _pytest_ es más rápido y eficiente.
¿has probado a ejecutar `unittest` en vez de `pytest`? ¿Existe siquiera?

2021-11-21 09:39 UTC, Antobio17 commented on docs/tests.md
> +En _Python_ existen varios framework y librerías para la construcción de tests, para este proyecto se van a tener en cuenta dos de ellas, **Pytests** y **Unittest**.
Si tiene razón, no se como he podido mezclar aquí los frameworks con las libs.

2021-11-21 09:39 UTC, Antobio17 commented on docs/tests.md
> +También destacar que según he podido [leer](https://www.pythonpool.com/python-unittest-vs-pytest/), _pytest_ es más rápido y eficiente.
Si, de hecho estuve viendo las distintas salidas de unittest, el fallo está en que no volví a la documentación para modificar y añadir aquello que había testeado.

2021-11-21 09:41 UTC, Antobio17 commented
@JJ quería preguntarle si ahora que el Objetivo-2 está aceptado en mi repositorio podría cerrar esta rama y reabrirla con el objetivo 2 ya mergeado, realizar los fixs que me indicó en ese y "desmenuzar" mas los issues de este, mejorar documentación etc.
Quería preguntarle también si podría hacer una refactorización de **naming** sobre la entidad y objetos valor del Objetivo-2.

2021-11-21 09:41 UTC, JJ commented
¿Qué salidas viste de unittest? Si no existe tal comando

2021-11-21 09:42 UTC, JJ commented
> @JJ quería preguntarle si ahora que el Objetivo-2 está aceptado en mi repositorio podría cerrar esta rama y reabrirla con el objetivo 2 ya mergeado, realizar los fixs que me indicó en ese y "desmenuzar" mas los issues de este, mejorar documentación etc. Quería preguntarle también si podría hacer una refactorización de **naming** sobre la entidad y objetos valor del Objetivo-2.

Puedes hacer lo que quieras, como es natural. Tendrás que hacer un merge a main, y una vez hecho eso un merge a la rama desde la que estás haciendo el PR del objetivo siguiente.

2021-11-21 09:44 UTC, Antobio17 commented
> ¿Qué salidas viste de unittest? Si no existe tal comando

Con los flags que tiene de ejecución el comando: `python unittest`

2021-11-21 09:46 UTC, Antobio17 commented
> > @JJ quería preguntarle si ahora que el Objetivo-2 está aceptado en mi repositorio podría cerrar esta rama y reabrirla con el objetivo 2 ya mergeado, realizar los fixs que me indicó en ese y "desmenuzar" mas los issues de este, mejorar documentación etc. Quería preguntarle también si podría hacer una refactorización de **naming** sobre la entidad y objetos valor del Objetivo-2.
> 
> Puedes hacer lo que quieras, como es natural. Tendrás que hacer un merge a main, y una vez hecho eso un merge a la rama desde la que estás haciendo el PR del objetivo siguiente.

Si, me refería a que como para empezar este objetivo hice un merge del Objetivo-2 aún estaba en construcción, si podría "reiniciar" este objetivo cerrando este PR y abriendo uno nuevo para así también no cerrar los issues referidos a los tests y especificarlos mas detalladamente como me ha indicado. En su momento no vi mala idea explicar todo en un issue pero si es verdad que los tests siempre van a ir creciendo y que un issue sea _Desarrollo de tests_ puede ser confuso.

2021-11-21 09:49 UTC, JJ commented
> > ¿Qué salidas viste de unittest? Si no existe tal comando
> 
> Con los flags que tiene de ejecución el comando: `python unittest`

De veras, Antonio, ese comando no existe. Ejecútalo y verás. `python` no tiene subcomandos, y si le dices eso lo que te va a buscar es un fichero que se llame unittest para ejecutarlo.

2021-11-21 09:49 UTC, JJ commented
> > > @JJ quería preguntarle si ahora que el Objetivo-2 está aceptado en mi repositorio podría cerrar esta rama y reabrirla con el objetivo 2 ya mergeado, realizar los fixs que me indicó en ese y "desmenuzar" mas los issues de este, mejorar documentación etc. Quería preguntarle también si podría hacer una refactorización de **naming** sobre la entidad y objetos valor del Objetivo-2.
> > 
> > 
> > Puedes hacer lo que quieras, como es natural. Tendrás que hacer un merge a main, y una vez hecho eso un merge a la rama desde la que estás haciendo el PR del objetivo siguiente.
> 
> Si, me refería a que como para empezar este objetivo hice un merge del Objetivo-2 aún estaba en construcción, si podría "reiniciar" este objetivo cerrando este PR y abriendo uno nuevo para así también no cerrar los issues referidos a los tests y especificarlos mas detalladamente como me ha indicado. En su momento no vi mala idea explicar todo en un issue pero si es verdad que los tests siempre van a ir creciendo y que un issue sea _Desarrollo de tests_ puede ser confuso.

No es confuso, sino erróneo, porque un issue debe plantear un problema. Cuando esté listo este issue pones el comentario.

2021-11-21 09:54 UTC, Antobio17 commented
> > > ¿Qué salidas viste de unittest? Si no existe tal comando
> > 
> > 
> > Con los flags que tiene de ejecución el comando: `python unittest`
> 
> De veras, Antonio, ese comando no existe. Ejecútalo y verás. `python` no tiene subcomandos, y si le dices eso lo que te va a buscar es un fichero que se llame unittest para ejecutarlo.

Antes habría que instalar la libreria de tests. Uno de los sitios donde estube buscando información fué [aquí](https://docs.python.org/3/library/unittest.html), donde muestra como ejecutar por línea de comandos.

2021-11-21 10:25 UTC, Antobio17 commented
> > > > @JJ quería preguntarle si ahora que el Objetivo-2 está aceptado en mi repositorio podría cerrar esta rama y reabrirla con el objetivo 2 ya mergeado, realizar los fixs que me indicó en ese y "desmenuzar" mas los issues de este, mejorar documentación etc. Quería preguntarle también si podría hacer una refactorización de **naming** sobre la entidad y objetos valor del Objetivo-2.
> > > 
> > > 
> > > Puedes hacer lo que quieras, como es natural. Tendrás que hacer un merge a main, y una vez hecho eso un merge a la rama desde la que estás haciendo el PR del objetivo siguiente.
> > 
> > 
> > Si, me refería a que como para empezar este objetivo hice un merge del Objetivo-2 aún estaba en construcción, si podría "reiniciar" este objetivo cerrando este PR y abriendo uno nuevo para así también no cerrar los issues referidos a los tests y especificarlos mas detalladamente como me ha indicado. En su momento no vi mala idea explicar todo en un issue pero si es verdad que los tests siempre van a ir creciendo y que un issue sea _Desarrollo de tests_ puede ser confuso.
> 
> No es confuso, sino erróneo, porque un issue debe plantear un problema. Cuando esté listo este issue pones el comentario.

Ya he definido los nuevos issues #26 #29 #30 #31 que corresponden a la implementación de los tests de este obejtivo.

2021-11-21 18:44 UTC, Antobio17 commented
@JJ listo para revisión.

2021-11-21 18:55 UTC, JJ approved these changes
Seguís con las malas prácticas en los mensajes de commit, pero eso ya no se puede cambiar. Por ejemplo 0ad615413a760c72e7aa4d023d6e0a8816bd0a3a sólo repite el issue. Los issues además, no pueden ser sólo de test, sino de funcionalidad *y* test. Hazlo así en lo sucesivo.

2021-11-21 19:01 UTC, Antobio17 commented
> Seguís con las malas prácticas en los mensajes de commit, pero eso ya no se puede cambiar. Por ejemplo [0ad6154](https://github.com/Antobio17/IV/commit/0ad615413a760c72e7aa4d023d6e0a8816bd0a3a) sólo repite el issue. Los issues además, no pueden ser sólo de test, sino de funcionalidad _y_ test. Hazlo así en lo sucesivo.

Al cambiar el issue que primeramente había hecho, commitear y después crear los nuevos quedaban sin cerrar si.

Respecto a los issues solo de tests es cierto error mio, lo tendré en cuenta para el futuro, gracias :pray:

2021-11-21 20:01 UTC, merged