[IV-21-22] Objetivo 5
Antobio17/IV pull request #35
Opened 2021-11-23 21:02 UTC by Antobio17

Se ha trabajado en los puntos para la superación del objetivo 5.

Se ha creado un Dockerfile para la contenerización de la aplicación justificado todas las decisiones en el _issue_ correspondiente (closes #34) y en la documentación del proyecto.
 
Se ha creado una **Github Action** para la subida y construcción de la imagen Docker a **Dockerhub** justificando las decisiones en su issue correspondiente (closes #33) al igual que el caso anterior.

2021-11-24 18:16 UTC, Antobio17 commented
@JJ listo para revisión.

2021-11-24 18:33 UTC, Antobio17 commented
@JJ listo para revisión.

2021-11-26 11:20 UTC, JJ requested changes
Por favor, revisa la justificación y el resto de los comentarios.

2021-11-26 11:20 UTC, JJ commented on .github/workflows/dockerhub.yml
> +      - 'Objetivo-**'
¿Y en main?

2021-11-26 11:20 UTC, JJ commented on .github/workflows/dockerhub.yml
> +      - main
¿En main sólo si es un PR?

2021-11-26 11:20 UTC, JJ commented on .github/workflows/dockerhub.yml
> +      - name: Extracción de metadatos para Docker
¿Estás seguro de que estás usando este paso? ¿Recuerdas que os expliqué en clase para qué servía?

2021-11-26 11:20 UTC, JJ commented on Dockerfile
> +    # Flag -S: creamos usuario de sistema.
¿de sistema?

2021-11-26 11:20 UTC, JJ commented on Dockerfile
> +COPY requirements.txt tasks.py /app/test/
¿Sigues usando requirements.txt? ¿Qué os he dicho sobre esto en clase?

2021-11-26 11:20 UTC, JJ commented on Dockerfile
> +COPY requirements.txt tasks.py /app/test/
Los estás copiando además a directorios que van a ser pisados cuando se monte la imagen externa.

2021-11-26 11:20 UTC, JJ commented on docs/docker.md
> +Unas de las primeras opciones consideradas como contenedor base ha sido `python:3.8.0-alpine`, sin embargo buscando información he encontrado que puede causar algunos problemas la contrucción de un c
Y la última, aparentemente, porque es la que usas.

2021-11-26 11:20 UTC, JJ commented on docs/docker.md
> +> Most Python packages these days include binary wheels on PyPI, significantly speeding install time. But if you’re using Alpine Linux you need to compile all the C code in every Python package that
¿Y esto en qué influye para el contenedor de test?

2021-11-26 11:20 UTC, JJ commented on docs/docker.md
> +Como podemos observar el tiempo es muy similar, únicamente se diferencian en un segundo.
Bien curradas las pruebas, pero el tiempo de construcción no tiene la más mínima importancia, y menos para tests. Lo que importa es el tiempo de ejecución.

2021-11-26 11:33 UTC, Antobio17 commented on .github/workflows/dockerhub.yml
> +      - main
Si, de hecho solo quería dejar que se lanzara la acción cuando es un PR, pero añadí las ramas para poder testear la subida a Dockerhub.

2021-11-26 11:34 UTC, Antobio17 commented on .github/workflows/dockerhub.yml
> +      - name: Extracción de metadatos para Docker
Efectivamente, no lo estoy usando. Lo dejé en la Github Action por si en un futuro me parecía interesante su uso. Lo elimino.

2021-11-26 11:36 UTC, Antobio17 commented on docs/docker.md
> +> Most Python packages these days include binary wheels on PyPI, significantly speeding install time. But if you’re using Alpine Linux you need to compile all the C code in every Python package that
Me parecía una frase interesante a destacar, era unicamente informativo ya que en mi caso no he tenido la necesidad de hacerlo.

2021-11-26 11:37 UTC, Antobio17 commented on docs/docker.md
> +Como podemos observar el tiempo es muy similar, únicamente se diferencian en un segundo.
Creía que el tiempo de construcción también influía ya que afectaría el tamaño de la imagen base, las dependencias instaladas, etc.

2021-11-26 11:42 UTC, Antobio17 commented on Dockerfile
> +    # Flag -S: creamos usuario de sistema.
Fallo mio, no actualicé la anotación, la creación es el grupo del sistema. Realmente no afecta en crear al usuario, únicamente a los uids asignados a los usuarios del grupo.

2021-12-02 20:31 UTC, Antobio17 commented
@JJ listo para revisión.
- Se ha modificado la gestión de dependencias justificando las decisiones tomadas
- Se ha vuelto a testear las imáneges base y se ha completado la documentación.

2021-12-05 20:09 UTC, JJ approved these changes
:+1:

2021-12-05 20:09 UTC, JJ commented on docs/docker.md
> +Para medir el tiempo que tarda en ejecutarse nuestros tests en el contenedor vamos a lanzar el siguiente comando (la imagen docker debe está subida a Dockerhub):
¿Dónde está ese tiempo?

2021-12-05 20:09 UTC, JJ commented on docs/docker.md
> +Como podemos observar el tiempo de construcción del contenedor es bastante significativo pero el importante, el tiempo de ejecución de los tests, es el mismo.
Con 2 centésimas de segundo no vas a observar mucha diferencia... Pero bueno, por lo menos lo has intentado.

2021-12-05 20:34 UTC, Antobio17 commented on docs/docker.md
> +Para medir el tiempo que tarda en ejecutarse nuestros tests en el contenedor vamos a lanzar el siguiente comando (la imagen docker debe está subida a Dockerhub):
Si se refiere al de la ejecución de los tests sí, son esas dos centesimas de segundo que se obtiene en la salida por consola.

2021-12-05 20:34 UTC, merged