Objetivo 1
Antobio17/IV pull request #5
Opened 2021-09-23 20:38 UTC by Antobio17

Se continua trabajando en la documentación del repositorio.
Se crea nuevo directorio para almacenar documentación adicional.
Se crea archivo markdown para documentación de Issues.

2021-09-24 05:19 UTC, JJ requested changes
1. Ninguna de las historias de usuario incluye una lógica de negocio adecuada.
2. No hay una descripción de las características del cliente
3. Los hitos deben ser productos mínimamente viables, no funcionalidades.

2021-09-24 15:36 UTC, JJ requested changes
En #6 (en toda historia, en general) tienes que especificar cuál es el contexto. ¿En base a qué se va a generar el pedido?)
En #7 igual. ¿Qué quieres obtener como resultado? ¿Qué quieres mejorar u optimizar? ¿Qué se va a hacer con el resultado de esa categorización? Esta es la lógica de negocio que se busca.
En #2, esa es una solución a un problema, no una especificación de historia de usuario. Tampoco tengo el contexto. ¿En base a qué vas a maximizarla?
Por otro lado, los hitos siguen sin ser productos mínimamente viables. Por favor, entiende del guión y la presentación de hoy (o cualquier otro medio) qué es un MVP y actúa en consecuencia.

2021-09-24 15:36 UTC, JJ commented on README.md
> +Además otro de los problemas que aparecen es la cantidad de articulos en el pedido mensual de productos para el negocio. Estos productos son utilizados para las citas y dependiendo del tipo de cita s
OK, como problema parece que tiene un potencial de generar una lógica de negocio adecuada, aunque me habría gustado que especificaras un poco más is vas a predecir algo. No queda muy claro en las citas qué es lo que vas a hacer con ellas.

2021-09-26 08:14 UTC, JJ commented on README.md
> +Se propone por tanto un sistema de gestión de cita previa "inteligente" que dependiendo del tipo de cita, el tipo de cliente (atendiento a la categorización del mismo), y el calendario del negocio, o
No acabo de entender el problema ni por qué la categorización puede afectar a que se vayan a compraro no cosas y maximizar los beneficios. Por eso precisamente es por lo que se solicita un user journey: qué es lo que haría el usuario interaccionando cn el sistema, qué obtendria, qué beneficios quiere obtener y cómo querría obtenerlos. Ten en cuenta que las historias de usuario son guías para programar, así que la ambigüedad no ayuda.

2021-09-26 08:16 UTC, JJ requested changes
Por favor, consulta el guión de la práctica sobre lo que constituiría un milestone y lo que no. Los milestones son productos mínimamente viables, no subsistemas o grupos de funcionalidades.

2021-09-26 09:38 UTC, JJ commented on README.md
> +Se propone por tanto un sistema de gestión de cita previa "inteligente" que dependiendo del tipo de cita, el tipo de cliente (atendiento a la categorización del mismo), y el calendario del negocio, o
A menos que digas claramente cómo se van a reducir las cancelaciones es muy complicado que puedas seguir adelante (y hacer una implementación).

2021-09-26 09:39 UTC, JJ commented on README.md
> +Esta maximización de ingresos se conseguirá reduciendo las cancelaciones imprevistas (estudio de los clientes para categorización) o reduciendo los tramos horarios en los que un trabajador no tiene c
Esto se trata simplemente de encontrar el primer hueco libre, y sólo es "almacena y busca"

2021-09-26 09:40 UTC, JJ commented on README.md
> +También se propone un sistema de gestión de pedidos mensuales para ajustar el gasto a las necesidades de la barbería.
¿Y de qué forma este tipo de aplicación sería más adecuado hacerlo en la nube que un app que puedas tener en un tablet, por ejemplo?

2021-09-28 13:38 UTC, Antobio17 commented
Listo para revisión.

2021-09-28 15:16 UTC, JJ approved these changes
La verdad es que has hecho un buen trabajo de caracterización del problema, y por eso voy a considerar el objetivo como cumplido. Sin embargo
1. Tienes que afinar un poco más los usuarios. ¿Quién reserva? ¿El cliente o alguien que está especializado en el tema'
2. ¿Va a haber un usuario que tome decisiones "estratégicas" o va a ser simplemente un algoritmo? En caso de que sea un algoritmo, ¿algún usuario específico recibirá informes sobre cómo ha funcionado?

Por otro lado, como a todo el mundo, tienes que afinar bien qué producto quieres en cada milestone. Sobre todo pensando en la persona a la que le va a tocar.

2021-09-28 15:57 UTC, Antobio17 commented
Muchas gracias. ¿Sigo entonces con las mejoras en esta misma rama y pull request?¿O cierro este, trabajo lo comentado en una rama aparte y creo el nuevo pr a mi repositorio cuando lo complete?

2021-09-29 05:17 UTC, JJ commented
Para ser honesto, ahora mismo prefiero que los cambios después de la aceptación los hagáis en otra rama. Si los hacéis en esta voy a recibir notificación... Y ya recibo bastantes. Por esta vez, está bien. Pero bien hecho, y buena preocupación por la calidad.

2021-09-29 06:02 UTC, Antobio17 commented
Perfecto, gracias. Mergeo esta rama y sigo trabajando en otra.

2021-09-29 06:02 UTC, merged